#ifndef DIRECTION_H
#define DIRECTION_H

enum class Direction
{
	AT_THE_STATION = '0', NORTH_EAST, EAST, SOUTH_EAST, SOUTH, SOUTH_WEST, WEST, NORTH_WEST, NORTH, ALL_DIRECTIONS
};

#endif /* DIRECTION_H */
