#ifndef NEBULOSITY_H
#define NEBULOSITY_H

/**
 * Nebulosity
 *
 * N: Total Cloud cover
 * N_h: Amount of all the C_L cloud present or, if no C_L cloud is present, the amount of all the C_M cloud present
 * @see table 2700, A-313
 */
enum class Nebulosity
{
	ZERO = '0',
	ONE_OR_LESS,
	TWO,
	THREE,
	FOUR,
	FIVE,
	SIX,
	SEVEN,
	EIGHT,
	OBSCURED_BY_FOG_OR_OTHER,
	NOT_OBSERVED = '/'
};

/**
* Clouds of the genera stratocumulus, stratus,cumulus and cumulonimbus
* @see table 0513, A-264
*/
enum class LowClouds
{
	NO_LOW_CLOUDS = '0',
	HUMILIS_OR_FRACTUS,
	MEDIOCRIS_OR_CONGESTUS,
	CALVUS,
	CUMULOGENITUS,
	OTHER_STRATOCUMULUS,
	NEBULOSUS_OR_FRACTUS,
	FRACTUS_OR_PANNUS,
	OTHER_CUMULUS,
	CAPILLATUS,
	NOT_OBSERVED = '/'
};

enum class MediumClouds
{
	NO_MEDIUM_CLOUDS = '0',
	ALTOSTATUS_TRANSLUCIDUS,
	ALTOSTATUS_OPACUS_OR_NIMBOSTRATUS,
	ALTOCUMULUS_TRANSLUCIDUS_SINGLE_LEVEL,
	PATCHES_ALTOCUMULUS_TRANSLUCIDUS_CHANGING,
	ALTOCUMULUS_TRANSLUCIDUS_INVADING,
	ALTOCUMULUS_CUMULOGENITUS,
	ALTOCUMULUS_SEVERAL_LAYERS,
	CASTELLANUS_OR_FLOCCUS,
	CHAOTIC,
	NOT_OBSERVED = '/'
};

enum class HighClouds
{
	NO_HIGH_CLOUDS = '0',
	CIRRUS_FIBRATUS_OR_UNCINUS,
	CIRRUS_SPISSATUS_OR_CASTELLANUS_OR_FLOCCUS,
	CIRRUS_SPISSATUS_CUMULONIMBOGENITUS,
	CIRRUS_FIBRATUS_OR_UNCINUS_INVADING,
	CIRROSTRATUS_INVADING,
	CIRROSTRATUS_INVADING_EXTENDED,
	CIRROSTRATUS_COVERING,
	CIRROSTRATUS_NOT_INVADING,
	CIRROCUMULUS,
	NOT_OBSERVED = '/'
};

#endif /* NEBULOSITY_H */
